/**
 * 各分类入口热度排序（知名度 / 用户量 / 行业影响力，2025–2026 参考）
 * 分数越高越靠前；未收录条目保持 HTML 原顺序垫底
 */
(function (global) {
  function entryKey(href) {
    try {
      const u = new URL(href);
      const host = u.hostname.toLowerCase().replace(/^www\./, '');
      let path = u.pathname.replace(/\/$/, '') || '';
      if (!path || path === '/') return host;
      return host + path;
    } catch {
      return String(href || '').toLowerCase();
    }
  }

  function hostOnly(href) {
    try {
      return new URL(href).hostname.toLowerCase().replace(/^www\./, '');
    } catch {
      return '';
    }
  }

  /** @param {string[]} keys 从前到后：热度从高到低 */
  function orderToScores(keys) {
    const m = {};
    keys.forEach((k, i) => {
      m[k] = (keys.length - i) * 10;
    });
    return m;
  }

  const CAT_ORDER = {
    'cn-chat': [
      'doubao.com',
      'chat.deepseek.com',
      'tongyi.aliyun.com',
      'kimi.moonshot.cn',
      'yiyan.baidu.com',
      'chatglm.cn',
      'yuanbao.tencent.com',
      'xinghuo.xfyun.cn',
      'tiangong.cn',
      'metaso.cn',
      'zhida.zhihu.com',
      'coze.cn',
      'hailuoai.com',
      'volcengine.com/product/doubao',
      'bailian.console.aliyun.com',
      'cloud.tencent.com/product/hunyuan',
      'n.cn',
      'stepfun.com',
      'baichuan-ai.com',
      'chat.sensetime.com',
      'platform.moonshot.cn',
      'ai.wps.cn',
      'feishu.cn/product/ai',
      'dingtalk.com',
      'huaweicloud.com/product/pangu.html',
      'lingyiwanwu.com',
      'modelbest.cn',
      'yanxi.jd.com',
      'ai.youdao.com',
      'jiutian.10086.cn',
      'mobvoi.com',
      'xiaoice.com',
      'ai.sohu.com',
      'langboat.com',
      'deeplang.ai',
      'ai.lenovo.com.cn',
    ],
    'global-chat': [
      'chatgpt.com',
      'claude.ai',
      'gemini.google.com',
      'copilot.microsoft.com',
      'perplexity.ai',
      'grok.com',
      'meta.ai',
      'platform.openai.com',
      'console.anthropic.com',
      'poe.com',
      'chat.mistral.ai',
      'notebooklm.google.com',
      'aistudio.google.com',
      'openrouter.ai',
      'chat.deepseek.com',
      'huggingface.co/chat',
      'ai.azure.com',
      'console.groq.com',
      'api.together.xyz',
      'cohere.com',
      'coze.com',
      'lmarena.ai',
      'github.com/marketplace/models',
      'aws.amazon.com/q',
      'duck.ai',
      'brave.com/leo',
      'you.com',
      'character.ai',
      'pi.ai',
      'reka.ai',
      'studio.ai21.com',
      'ibm.com/products/watsonx-ai',
      'abacus.ai',
      'venice.ai',
      'getliner.com',
      'writer.com',
    ],
    multimodal: [
      'chatgpt.com',
      'gemini.google.com',
      'claude.ai',
      'doubao.com',
      'tongyi.aliyun.com',
      'kimi.moonshot.cn',
      'grok.com',
      'yiyan.baidu.com',
      'yuanbao.tencent.com',
      'xinghuo.xfyun.cn',
      'hailuoai.com',
      'stepfun.com',
    ],
    'ai-search': [
      'perplexity.ai',
      'metaso.cn',
      'kimi.moonshot.cn',
      'tiangong.cn',
      'you.com',
      'phind.com',
      'consensus.app',
      'elicit.com',
      'chat.baidu.com',
      'n.cn',
      'zhida.zhihu.com',
      'xueshu.baidu.com',
    ],
    media: [
      'midjourney.com',
      'openai.com/sora',
      'runwayml.com',
      'klingai.kuaishou.com',
      'jimeng.jianying.com',
      'firefly.adobe.com',
      'blackforestlabs.ai',
      'lumalabs.ai',
      'tongyi.aliyun.com/wanxiang',
      'hailuoai.com/video',
      'vidu.studio',
      'pixverse.ai',
      'yige.baidu.com',
      'whee.com',
    ],
    audio: [
      'suno.com',
      'elevenlabs.io',
      'udio.com',
      'heygen.com',
      'd-id.com',
      'fish.audio',
      'zenvideo.qq.com',
      'moyin.com',
      'xfyun.cn/services/online_tts',
      'guiji.cn',
      'tianpuyue.cn',
    ],
    'video-edit': [
      'capcut.com',
      'capcut.cn',
      'opus.pro',
      'descript.com',
      'veed.io',
      'pika.art',
      'zenvideo.qq.com',
      'laihua.com',
      'member.bilibili.com/platform/upload/video/frame',
    ],
    '3d-game': [
      'meshy.ai',
      'tripo3d.ai',
      '3d.hunyuan.tencent.com',
      'spline.design',
      'unity.com/products/muse',
      'hyperhuman.deemos.com',
    ],
    'design-ui': [
      'figma.com/ai',
      'v0.dev',
      'framer.com',
      'webflow.com',
      'uizard.io',
      'relume.io',
      'js.design',
      'mastergo.com',
      'pixso.cn',
      'mockplus.cn',
      'lanhuapp.com',
    ],
    coding: [
      'cursor.com',
      'github.com/features/copilot',
      'codeium.com/windsurf',
      'anthropic.com/claude-code',
      'v0.dev',
      'bolt.new',
      'replit.com',
      'lovable.dev',
      'trae.cn',
      'marscode.cn',
      'tongyi.aliyun.com/lingma',
      'comate.baidu.com',
      'codegeex.cn',
    ],
    workflow: [
      'coze.cn',
      'dify.ai',
      'n8n.io',
      'fastgpt.in',
      'ragflow.io',
      'zapier.com',
      'make.com',
      'langflow.org',
      'cloud.baidu.com/product/wenxinworkshop',
      'maxkb.fit2cloud.com',
      'xfyun.cn',
    ],
    'api-dev': [
      'platform.openai.com',
      'console.anthropic.com',
      'platform.deepseek.com',
      'bailian.console.aliyun.com',
      'console.volcengine.com/ark',
      'open.bigmodel.cn',
      'cloud.siliconflow.cn',
      'openrouter.ai',
      'cloud.tencent.com/product/hunyuan',
      'xfyun.cn',
    ],
    opensource: [
      'ollama.com',
      'huggingface.co',
      'lmstudio.ai',
      'modelscope.cn',
      'github.com/open-webui/open-webui',
      'jan.ai',
      'localai.io',
      'aistudio.baidu.com',
    ],
    'model-host': [
      'replicate.com',
      'fal.ai',
      'fireworks.ai',
      'civitai.com',
      'cloud.siliconflow.cn',
      'modelscope.cn',
      'modelscope.cn/models',
      'hyperbolic.xyz',
    ],
    'gpu-cloud': [
      'autodl.com',
      'runpod.io',
      'aliyun.com/product/gpu',
      'cloud.tencent.com/product/gpu',
      'lambda.ai',
      'modal.com',
      'coreweave.com',
      'virtaicloud.com',
      'suanli.cn',
    ],
    office: [
      'notion.so/product/ai',
      'wps.cn',
      'feishu.cn',
      'canva.com',
      'gamma.app',
      'figma.com/ai',
      'dingtalk.com',
      'grammarly.com',
      'miro.com/ai',
      'aippt.cn',
      'islide.cc',
      'shimo.im',
    ],
    meeting: [
      'microsoft.com/microsoft-365/copilot',
      'meeting.tencent.com',
      'feishu.cn/product/minutes',
      'otter.ai',
      'fireflies.ai',
      'iflyrec.com',
      'notta.ai',
      'tldv.io',
      'dingtalk.com',
      'meeting.tencent.com/ai',
    ],
    translate: [
      'deepl.com',
      'translate.google.com',
      'fanyi.baidu.com',
      'fanyi.youdao.com',
      'immersivetranslate.com',
      'deepl.com/write',
      'otranslator.com',
      'tongyi.aliyun.com',
    ],
    data: [
      'microsoft.com/copilot',
      'powerbi.microsoft.com',
      'tableau.com',
      'databricks.com',
      'julius.ai',
      'rows.com',
      'ai.wps.cn',
      'chatexcel.com',
      'aliyun.com/product/bigdata/bi',
      'fanruan.com/finebi',
      'sensorsdata.cn',
    ],
    'email-eff': [
      'superhuman.com',
      'notion.so/product/mail',
      'shortwave.com',
      'reclaim.ai',
      'usemotion.com',
      'dida365.com',
    ],
    pkm: [
      'notion.so/product/ai',
      'obsidian.md',
      'yuque.com',
      'logseq.com',
      'xmind.ai',
      'v.flomoapp.com',
    ],
    crm: [
      'salesforce.com/agentforce',
      'intercom.com/ai',
      'zendesk.com/service/ai',
      'hubspot.com/products/ai',
      'sobot.com',
      'qiyukf.com',
      'udesk.cn',
      'easemob.com',
    ],
    hr: [
      'linkedin.com',
      'mokahr.com',
      'beisen.com',
      'eightfold.ai',
      'huntr.co',
      'joinhandshake.com',
    ],
    marketing: [
      'canva.com',
      'capcut.cn',
      'jasper.ai',
      'copy.ai',
      'writesonic.com',
      'oceanengine.com',
      'ad.qq.com',
      'xiaohongshu.com',
      'chuangyi.taobao.com',
      'hubspot.com/products/ai',
      'adobe.com/sensei.html',
    ],
    'writing-long': [
      'sudowrite.com',
      'novelai.net',
      'ibiling.cn',
      'wawawriter.com',
      'if.caiyunai.com',
      'squibler.io',
    ],
    edu: [
      'notebooklm.google.com',
      'coursera.org',
      'khanacademy.org',
      'duolingo.com',
      'semanticscholar.org',
      'consensus.app',
      'connectedpapers.com',
      'quizlet.com',
      'icourse163.org',
      'xuetangx.com',
      'tianchi.aliyun.com',
      'ai.youdao.com',
    ],
    vertical: [
      'openai.com/enterprise',
      'bloomberg.com/professional',
      'harvey.ai',
      'casetext.com',
      'hebbia.ai',
      'wind.com.cn',
      'iwencai.com',
      'pkulaw.com',
      'law.wkinfo.com.cn',
      'nuance.com/healthcare.html',
    ],
    trust: [
      'gptzero.me',
      'copyleaks.com',
      'originality.ai',
      'lakera.ai',
      'protectai.com',
      'hivemoderation.com',
      'matrix.tencent.com/ai-detect',
      'dun.163.com',
      'ai.baidu.com/solution/antiporn',
    ],
    compare: [
      'lmarena.ai',
      'chat.lmsys.org',
      'artificialanalysis.ai',
      'superclueai.com',
      'opencompass.org.cn',
      'swebench.com',
      'huggingface.co/spaces',
      'modelscope.cn/models',
      'flagopen.baai.ac.cn',
    ],
    'prompt-community': [
      'coze.cn',
      'monica.im',
      'sider.ai',
      'waytoagi.com',
      'flowgpt.com',
      'promptingguide.ai',
      'glama.ai',
      'maxai.me',
      'aishort.top',
      'promptbase.com',
    ],
  };

  const CAT_SCORES = {};
  Object.keys(CAT_ORDER).forEach((id) => {
    CAT_SCORES[id] = orderToScores(CAT_ORDER[id]);
  });

  /** 跨分类通用热度（分类未单独定义时的兜底） */
  const GLOBAL = orderToScores([
    'chatgpt.com',
    'claude.ai',
    'gemini.google.com',
    'openai.com',
    'anthropic.com',
    'google.com',
    'microsoft.com',
    'meta.ai',
    'deepseek.com',
    'doubao.com',
    'tongyi.aliyun.com',
    'kimi.moonshot.cn',
    'baidu.com',
    'tencent.com',
    'aliyun.com',
    'bytedance.com',
    'huggingface.co',
    'github.com',
    'notion.so',
    'figma.com',
  ]);

  function score(catId, href) {
    const key = entryKey(href);
    const host = hostOnly(href);
    const cat = CAT_SCORES[catId];
    if (cat) {
      if (cat[key] != null) return cat[key];
      if (cat[host] != null) return cat[host];
    }
    if (GLOBAL[host] != null) return GLOBAL[host];
    if (GLOBAL[key] != null) return GLOBAL[key];
    return 0;
  }

  global.HubHeat = { score, entryKey, hostOnly };
})(typeof window !== 'undefined' ? window : globalThis);
